#
## Avoid Hydra to generate outputs
#defaults:
#  - _self_
#  - override hydra/hydra_logging: disabled
#  - override hydra/job_logging: disabled

#hydra:
#  output_subdir: null
#  run:
#    dir: .

hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null
  
settings:
  data_source: ../data
  file_extension: .csv
  create_online_images: False # True / False
  show_images: False # True / False
  show_gif: False # True / False
  images_extension: .png
  data_output: ../Output_image_folder
  background_images_folder: ../Task_image_background
  output_directory_csv: ../Output_csv_folder
  output_directory_plots: ../Output_csv_for_plots
  output_task_3d: ../Output_3D_folder
  overwrite: False
  score_file: ../score_2023.csv
  in_air: False # if True, the task will be processed for InAir data only else for OnPaper data
  verbose: False
  plotting: False # enable plotting for the tasks
  feature_extraction: True # enable feature extraction for the tasks
  fs_approach: "Statistical" # Statistical / Stroke
  task_list: [1,2]  # list of tasks to be processed
  subject_task_to_plot: [138, 82, 97]  # list of subjects to be plotted

