#
## Avoid Hydra to generate outputs
#defaults:
#  - _self_
#  - override hydra/hydra_logging: disabled
#  - override hydra/job_logging: disabled

#hydra:
#  output_subdir: null
#  run:
#    dir: .

hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null
  
settings:
  data_source: ..\\data
  file_extension: .csv
  use_images: False
  images_extension: .png
  data_output: ..\\Output_image_folder
  background_images_folder: ..\\Task_image_background
  output_directory_csv: ..\\Output_csv_folder
  in_air: False
  verbose: False
  plotting: True
  feature_extraction: False
  task_list: [1,3,5,7]

