
# Avoid Hydra to generate outputs
defaults:  
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled    
  
settings:
  data_source: data
  file_extension: .csv
  images_extension: .png
  data_output: Output_image_folder
  background_images_folder: Task_image_background


hydra:  
  output_subdir: null  
  run:  
    dir: .