#
## Avoid Hydra to generate outputs
#defaults:
#  - _self_
#  - override hydra/hydra_logging: disabled
#  - override hydra/job_logging: disabled

#hydra:
#  output_subdir: null
#  run:
#    dir: .

hydra:
  job_logging:
    root:
      handlers: [console]
      level: INFO
      formatter: simple
    formatters:
      simple:
        format: "[%(asctime)s][%(filename)s][%(levelname)s] - %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"
  run:
    dir: .
  output_subdir: null
  
settings:
  data_source: ..\\data
  file_extension: .csv
  use_images: False
  images_extension: .png
  data_output: ..\\Output_image_folder
  background_images_folder: ..\\Task_image_background
  output_directory_csv: ..\\Output_csv_folder
  output_directory_plots: ..\\Output_csv_for_plots
  output_task_3d: ..\\Output_3D_folder
  overwrite: False
  score_file: ..\\score_2023.csv
  in_air: False
  verbose: False
  plotting: True
  feature_extraction: False
  task_list: [10,11,12,13,21] # [10,11,12,13,21] [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
  subject_task_to_plot: [138, 82, 97] # [138, 82, 97]

